config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => 'home#index'
  resources :users
  resources :comments
  resources :posts do
    resources :comments
  end
  resources :sessions
  resources :posts

  get '/signup' => 'users#new'
  get '/logout', to: 'sessions#destroy'
  get '/login', to: 'sessions#new'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, optional: true
  belongs_to :user, optional: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates_presence_of :email, :password, :fname, :lname, :age
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def logged_in?
    def logged_in?
      # ||= means 'or assign this value to a variable'
      # So if you did something like x ||= ythis meansx || x = y so if x is nil or false set x to be the value of y.
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end

  def new
    @comment = Comment.new(post_id: params[:post_id], user_id: session[:user_id])
  end

  def create
    user = User.find(session[:user_id])

    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    puts @post
    if @comment.save
      flash[:notice] = "Comment successfully added"
      user.comments << @comment
      redirect_to post_path(@post)
    else
      flash[:alert] = "Error posting comment"
      redirect_to post_path(@post)
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @post = Post.find(@comment.post_id)
    if @comment.destroy
      flash[:notice] = "Comment deleted"
      redirect_to post_path(@post)
    else
      flash[:alert] = "There was an issue deleting comment"
      redirect_to post_path(@post)
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    if session[:user_id]
      @user = User.find(session[:user_id])
    end
    @post = Post.find(params[:id])
    @comments = @post.comments
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @poster = User.find(session[:user_id])
    @post = @poster.posts.new(post_params)
    if @post.save
      flash[:notice] = "Your post was created successfully."
      # redirect_to root_path
      puts '@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@SUCCESS'
      redirect_to posts_path
    else
      flash[:alert] = "There was a problem creating your post."
      puts '@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@FAIL'
      redirect_to posts_path
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:notice] = "Post destroyed"
      redirect_to posts_path
    else
      flash[:alert] = "There was an issue deleting post"
      redirect_to posts_path(@post)
    end
  end

  private

    def post_params
      params.require(:post).permit(:content,:title)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.where(email: params[:email]).first
    if @user && @user.password == params[:password]
      session[:user_id] = @user.id
      puts 'SessionStart'+'@'*45
      flash[:notice] = "Logged in"
      redirect_to root_path
    else
      puts 'X'*30
      flash[:alert] = "Incorrect email or password"
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    puts 'SessionEnd'+'@'*45
    flash[:notice] = "Logged out successfully"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    # @user = User.new(params[:user])
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Your account was created successfully."
      session[:user_id] = @user.id
      # redirect_to root_path
      redirect_to root_path
    else
      flash[:alert] = "There was a problem saving your account."
      redirect_to root_path
    end
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)

    if @user.save
      flash[:notice] = "Your account was updated successfully."
      redirect_to users_path
    else
      flash[:alert] = "There was a problem updating your account."
      redirect_to edit_users_path
    end
  end

  def destroy
    puts 'HERE I AM'
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] = "User deleted successfully."
    else
      flash[:alert] = "An error occurred."
    end
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:email,:password,:fname,:lname,:age)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  #  helper_method :logged_in?
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/index.html.erb
Comment index

app/views/comments/show.html.erb
<h1>Comments show</h1>

app/views/home/index.html.erb
<div id="home" class="container">
  <%=image_tag("blog.jpg", width: '1000', class: '.img-responsive center-block')%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Rubik" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav>
      | <a href="/">Home</a> |
      <a href="/users">Users</a> |
      <a href="/posts">Posts</a> |
      <% if session[:user_id] %>
      <a href="/users/<%=session[:user_id]%>">Profile</a> |
      <a href="/logout">Logout</a> |
      <% else %>
      <a href="/login">Login</a> |
      <a href="/signup">Register</a> |
      <% end %>
    </nav>
    <div id="main" class="container">
      <div class="flashNotice">
        <% if flash[:notice] %>
        <%= flash[:notice] %>
        <% end %>
      </div>
      <div class="flashAlert">
        <% if flash[:alert] %>
        <%= flash[:alert] %>
        <% end %>
      </div>
    <%= yield %>
    </div>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Post index</h1><%= link_to "New Post", "posts/new" %>

<% @posts.reverse_each do |post| %>
<h2 class="post_title"> <%= link_to post.title, post_path(post) %></h2>
<p class="captions">posted <%= distance_of_time_in_words(post.created_at, Time.now) %> ago by <span><%= link_to "#{User.find(post.user_id).fname} #{User.find(post.user_id).lname}", user_path(post.user_id) %></span></p>
<%= link_to "Delete Post", post_path(post), method: :delete %>
<% end %>

<!-- distance_of_time_in_words(Time.now, TIme.now + 15.seconds) -->
<!-- select_date(Time.today + 10.days) -->
<!-- time_ago_in_words(3.minutes.from.now) -->

app/views/posts/new.html.erb
<h1>Post new</h1>

<%= form_for Post.new do |form| %>
<%= form.label :title %>
<%= form.text_field :title %>
<%= form.label :content %>
<%= form.text_field :content %>
<%= form.submit %>
<% end %>

app/views/posts/show.html.erb
<h2><%=@post.title%> </h2>
<p class="captions">posted <%= distance_of_time_in_words(@post.created_at, Time.now) %> ago by <span><%= link_to "#{User.find(@post.user_id).fname} #{User.find(@post.user_id).lname}", user_path(@post.user_id) %></span></p>


<p id="post_content"><%=@post.content%></p>

<h2>Comments</h2>
<% @comments.each do |comment| %>
<div class='comment_div'><p><%=comment.content%></p><br>
<p class="captions">commented <%= distance_of_time_in_words(comment.created_at, Time.now) %> ago by <span><%= link_to "#{User.find(comment.user_id).fname} #{User.find(comment.user_id).lname}", user_path(comment.user_id) %></span></p>
<%= link_to "Delete", comment_path(comment), method: :delete %>
</div>
<% end %>


<%= form_for ([@post,@post.comments.build]) do |f| %>
<%= f.label :content, "Comment" %>
<%= f.text_area :content %>
<%= f.submit %>
<% end %>

<!-- distance_of_time_in_words(Time.now, TIme.now + 15.seconds) -->

app/views/users/edit.html.erb
<%= form_for @user do |f|%>
<%= f.label :email %>
<%= f.text_field :email %>
<%= f.label :password %>
<%= f.password_field :password %>
<%= f.label :fname %>
<%= f.text_field :fname %>
<%= f.label :lname %>
<%= f.text_field :lname %>
<%= f.label :age %>
<%= f.number_field :age %>
<%= f.submit %>
<% end %>

app/views/users/index.html.erb
<div class="container">
  <h1 class="text-center">Users</h1>
  <div id="users_list">
    <% @users.each do |u| %>
    <%  if u.fname %>
    <%= link_to "#{u.fname} #{u.lname}", user_path(u), class: "body_link" %>
    <% else %>
    <%= link_to "Unknown", user_path(u) %>
    <% end %>
    <br>
    <% end %>
  </div>
</div>


<!-- sends delete rquest to user(5) -->

app/views/users/new.html.erb
<!-- <form class="" action="/users" method="post">
  First Name: <input type="text" name="fname" value="">
  Last Name: <input type="text" name="lname" value="">
  Age: <input type="number" name="age" value="">
  <input type="submit" name="" value="Submit">
</form> -->

<%= form_for User.new do |f| %>
<%= f.label :email %>
<%= f.text_field :email %>
<%= f.label :password %>
<%= f.password_field :password %>
<%= f.label :fname %>
<%= f.text_field :fname %>
<%= f.label :lname %>
<%= f.text_field :lname %>
<%= f.label :age %>
<%= f.number_field :age %>
<%= f.submit %> <% end %>

app/views/users/show.html.erb
<div id="profile_name" class="focus-in-expand"><%= @user.fname %> <%= @user.lname%></div><br>
<strong>Email: </strong><%= @user.email%>
<strong>Age: </strong><%= @user.age %><br>
<strong>User ID: </strong><%= @user.id %>
<%= link_to "Delete User", user_path(@user), method: :delete %>